// Minimal GeoSiteList/GeoSite/Domain proto for dlc.dat (v2fly domain-list-community).
// Copied from v2fly/v2ray-core app/router/routercommon/common.proto;
// no protoext import and no field 68000 to avoid extension 50000 conflict with grpc.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/geosite.proto

package dlcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Domain_Type int32

const (
	Domain_Plain      Domain_Type = 0
	Domain_Regex      Domain_Type = 1
	Domain_RootDomain Domain_Type = 2
	Domain_Full       Domain_Type = 3
)

// Enum value maps for Domain_Type.
var (
	Domain_Type_name = map[int32]string{
		0: "Plain",
		1: "Regex",
		2: "RootDomain",
		3: "Full",
	}
	Domain_Type_value = map[string]int32{
		"Plain":      0,
		"Regex":      1,
		"RootDomain": 2,
		"Full":       3,
	}
)

func (x Domain_Type) Enum() *Domain_Type {
	p := new(Domain_Type)
	*p = x
	return p
}

func (x Domain_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Domain_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_geosite_proto_enumTypes[0].Descriptor()
}

func (Domain_Type) Type() protoreflect.EnumType {
	return &file_proto_geosite_proto_enumTypes[0]
}

func (x Domain_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Domain_Type.Descriptor instead.
func (Domain_Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_geosite_proto_rawDescGZIP(), []int{0, 0}
}

// Domain for routing/geosite decision.
type Domain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          Domain_Type            `protobuf:"varint,1,opt,name=type,proto3,enum=ruledforward.dlc.Domain_Type" json:"type,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Attribute     []*Domain_Attribute    `protobuf:"bytes,3,rep,name=attribute,proto3" json:"attribute,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Domain) Reset() {
	*x = Domain{}
	mi := &file_proto_geosite_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Domain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Domain) ProtoMessage() {}

func (x *Domain) ProtoReflect() protoreflect.Message {
	mi := &file_proto_geosite_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Domain.ProtoReflect.Descriptor instead.
func (*Domain) Descriptor() ([]byte, []int) {
	return file_proto_geosite_proto_rawDescGZIP(), []int{0}
}

func (x *Domain) GetType() Domain_Type {
	if x != nil {
		return x.Type
	}
	return Domain_Plain
}

func (x *Domain) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Domain) GetAttribute() []*Domain_Attribute {
	if x != nil {
		return x.Attribute
	}
	return nil
}

type GeoSite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CountryCode   string                 `protobuf:"bytes,1,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	Domain        []*Domain              `protobuf:"bytes,2,rep,name=domain,proto3" json:"domain,omitempty"`
	ResourceHash  []byte                 `protobuf:"bytes,3,opt,name=resource_hash,json=resourceHash,proto3" json:"resource_hash,omitempty"`
	Code          string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoSite) Reset() {
	*x = GeoSite{}
	mi := &file_proto_geosite_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoSite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoSite) ProtoMessage() {}

func (x *GeoSite) ProtoReflect() protoreflect.Message {
	mi := &file_proto_geosite_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoSite.ProtoReflect.Descriptor instead.
func (*GeoSite) Descriptor() ([]byte, []int) {
	return file_proto_geosite_proto_rawDescGZIP(), []int{1}
}

func (x *GeoSite) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *GeoSite) GetDomain() []*Domain {
	if x != nil {
		return x.Domain
	}
	return nil
}

func (x *GeoSite) GetResourceHash() []byte {
	if x != nil {
		return x.ResourceHash
	}
	return nil
}

func (x *GeoSite) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type GeoSiteList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         []*GeoSite             `protobuf:"bytes,1,rep,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoSiteList) Reset() {
	*x = GeoSiteList{}
	mi := &file_proto_geosite_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoSiteList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoSiteList) ProtoMessage() {}

func (x *GeoSiteList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_geosite_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoSiteList.ProtoReflect.Descriptor instead.
func (*GeoSiteList) Descriptor() ([]byte, []int) {
	return file_proto_geosite_proto_rawDescGZIP(), []int{2}
}

func (x *GeoSiteList) GetEntry() []*GeoSite {
	if x != nil {
		return x.Entry
	}
	return nil
}

type Domain_Attribute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Domain_Attribute) Reset() {
	*x = Domain_Attribute{}
	mi := &file_proto_geosite_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Domain_Attribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Domain_Attribute) ProtoMessage() {}

func (x *Domain_Attribute) ProtoReflect() protoreflect.Message {
	mi := &file_proto_geosite_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Domain_Attribute.ProtoReflect.Descriptor instead.
func (*Domain_Attribute) Descriptor() ([]byte, []int) {
	return file_proto_geosite_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Domain_Attribute) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

var File_proto_geosite_proto protoreflect.FileDescriptor

const file_proto_geosite_proto_rawDesc = "" +
	"\n" +
	"\x13proto/geosite.proto\x12\x10ruledforward.dlc\"\xea\x01\n" +
	"\x06Domain\x121\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1d.ruledforward.dlc.Domain.TypeR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12@\n" +
	"\tattribute\x18\x03 \x03(\v2\".ruledforward.dlc.Domain.AttributeR\tattribute\x1a\x1d\n" +
	"\tAttribute\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"6\n" +
	"\x04Type\x12\t\n" +
	"\x05Plain\x10\x00\x12\t\n" +
	"\x05Regex\x10\x01\x12\x0e\n" +
	"\n" +
	"RootDomain\x10\x02\x12\b\n" +
	"\x04Full\x10\x03\"\x97\x01\n" +
	"\aGeoSite\x12!\n" +
	"\fcountry_code\x18\x01 \x01(\tR\vcountryCode\x120\n" +
	"\x06domain\x18\x02 \x03(\v2\x18.ruledforward.dlc.DomainR\x06domain\x12#\n" +
	"\rresource_hash\x18\x03 \x01(\fR\fresourceHash\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\">\n" +
	"\vGeoSiteList\x12/\n" +
	"\x05entry\x18\x01 \x03(\v2\x19.ruledforward.dlc.GeoSiteR\x05entryB;Z9github.com/hr3lxphr6j/coredns-ruledforward/internal/dlcpbb\x06proto3"

var (
	file_proto_geosite_proto_rawDescOnce sync.Once
	file_proto_geosite_proto_rawDescData []byte
)

func file_proto_geosite_proto_rawDescGZIP() []byte {
	file_proto_geosite_proto_rawDescOnce.Do(func() {
		file_proto_geosite_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_geosite_proto_rawDesc), len(file_proto_geosite_proto_rawDesc)))
	})
	return file_proto_geosite_proto_rawDescData
}

var file_proto_geosite_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_geosite_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_geosite_proto_goTypes = []any{
	(Domain_Type)(0),         // 0: ruledforward.dlc.Domain.Type
	(*Domain)(nil),           // 1: ruledforward.dlc.Domain
	(*GeoSite)(nil),          // 2: ruledforward.dlc.GeoSite
	(*GeoSiteList)(nil),      // 3: ruledforward.dlc.GeoSiteList
	(*Domain_Attribute)(nil), // 4: ruledforward.dlc.Domain.Attribute
}
var file_proto_geosite_proto_depIdxs = []int32{
	0, // 0: ruledforward.dlc.Domain.type:type_name -> ruledforward.dlc.Domain.Type
	4, // 1: ruledforward.dlc.Domain.attribute:type_name -> ruledforward.dlc.Domain.Attribute
	1, // 2: ruledforward.dlc.GeoSite.domain:type_name -> ruledforward.dlc.Domain
	2, // 3: ruledforward.dlc.GeoSiteList.entry:type_name -> ruledforward.dlc.GeoSite
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_geosite_proto_init() }
func file_proto_geosite_proto_init() {
	if File_proto_geosite_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_geosite_proto_rawDesc), len(file_proto_geosite_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_geosite_proto_goTypes,
		DependencyIndexes: file_proto_geosite_proto_depIdxs,
		EnumInfos:         file_proto_geosite_proto_enumTypes,
		MessageInfos:      file_proto_geosite_proto_msgTypes,
	}.Build()
	File_proto_geosite_proto = out.File
	file_proto_geosite_proto_goTypes = nil
	file_proto_geosite_proto_depIdxs = nil
}
